name: shelf_open_api_generator
description: Open api specs generators from dart code for shelf package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

scripts:
  # To generate .g files:
  # Comment `builders` key on build.yaml before launch this command
  build:runner: dart run build_runner watch -d

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_open_api:
    path: ../shelf_open_api

  collection: ^1.17.1
  stream_transform: ^2.1.0
  glob: ^2.1.1

  analyzer: ">=4.0.0 <6.0.0"
  build: ^2.3.1

  # OPEN API
  json_annotation: ^4.8.0

  # ROUTING
  source_gen: ^1.2.7

dev_dependencies:
  mek_lints: ^1.0.0

  test: ^1.23.1

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
