name: shelf_open_api_generator
description: Open api specs generators from dart code for shelf package.
repository: https://github.com/BreX900/open_api
issue_tracker: https://github.com/BreX900/open_api/issues
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

scripts:
  # To generate .g files:
  # Comment `builders` key on build.yaml before launch this command
  build:runner: dart run build_runner watch --delete-conflicting-outputs

dependencies:
  open_api_spec: ^1.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_open_api: ^1.0.0

  collection: ^1.17.1
  stream_transform: ^2.1.0
  glob: ^2.1.1

  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.3.1

  # OPEN API
  json_annotation: ^4.8.0

  # ROUTING
  source_gen: ^1.2.7

dev_dependencies:
  mek_lints: ^1.0.0

  test: ^1.23.1

  build_runner: ^2.3.3
  json_serializable: ^6.6.1

dependency_overrides:
  open_api_spec:
    path: ../open_api_spec
  shelf_open_api:
    path: ../shelf_open_api
