openapi: 3.0.0
info:
  title: Api
  version: 0.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /<intParameter>:
    get:
      tags:
        - PathParametersController
      summary: fetchMessages
      operationId: fetchMessages
      parameters:
        - name: intParameter
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /<stringParameter>:
    post:
      tags:
        - PathParametersController
      summary: createMessage
      operationId: createMessage
      parameters:
        - name: stringParameter
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /<decimalParameter>:
    put:
      tags:
        - PathParametersController
      summary: updateMessage
      operationId: updateMessage
      parameters:
        - name: decimalParameter
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /messages:
    get:
      tags:
        - QueryParametersController
      summary: fetchMessages
      operationId: fetchMessages
      responses:
        200:
          description: "Operation completed!"
  /chats:
    post:
      tags:
        - ChatsController
      summary: createChatForReport
      operationId: createChatForReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatCreateDto"
      responses:
        200:
          description: "Operation completed!"
  /chats/<chatId>:
    get:
      tags:
        - ChatsController
      summary: fetchChat
      operationId: fetchChat
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
components:
  schemas:
    ChatCreateDto:
      title: ChatCreateDto
      type: object
      properties:
        title:
          type: string
      required:
        - title
tags:
  - name: PathParametersController
  - name: MessagesController
  - name: QueryParametersController
  - name: ChatsController