name: open_api_client_generator
description: A sample command-line application.
publish_to: 'none'
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.7.0
  collection: ^1.17.0

  path: ^1.8.3
  http: ^1.1.0
  json2yaml: ^3.0.1

  analyzer: ^6.1.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  recase: ^4.1.0
  diacritic: ^0.1.4

  logging: ^1.2.0

  open_api_spec:
    path: ./../open_api_spec

  args: ^2.4.2

dev_dependencies:
  mek_lints: ^2.0.0

  dio: ^5.3.2
  json_annotation: ^4.8.1
  fast_immutable_collections: ^9.1.5
  built_value: ^8.6.2
  built_collection: ^5.1.1

  recase: ^4.1.0
