name: open_api_spec
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

scripts:
  build:library: index_generator
  # To generate .g files:
  build:runner: dart run build_runner watch --delete-conflicting-outputs

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.0

  path: ^1.8.3
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.6.1

index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  indexes:
    - path: ./lib
      include: [ src/specs/*.dart ]
    - path: ./lib
      name: open_api
      include: [ src/*.dart ]