targets:
  $default:
    builders:
      shelf_open_api_generator:
        enabled: false
      shelf_open_api_generator:shelf_routing:
        enabled: false

      json_serializable:
        generate_for:
          - lib/src/config.dart
        options:
          create_factory: false
          create_to_json: false

builders:
  shelf_routing_generator:router:
    import: package:shelf_routing_generator/run_routers_builder.dart
    builder_factories: [ 'runRoutersBuilder' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.routers.g.part', '.routers_groups.json' ] }
    auto_apply: dependents
    build_to: cache

  shelf_routing_generator:routing:
    import: package:shelf_routing_generator/run_routers_groups_builder.dart
    builder_factories: [ 'runRoutersGroupsBuilder' ]
    required_inputs: [ '.routers_groups.json' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.routers.dart' ] }
    auto_apply: dependents
    build_to: source



