targets:
  $default:
    builders:
      shelf_routing_generator:
        generate_for:
          - example/**
      shelf_routing_generator:groups:
        generate_for:
          - example/**

builders:
  shelf_routing_generator:
    import: package:shelf_routing_generator/run_routers_builder.dart
    builder_factories: [ 'runRoutersBuilder' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.routers.g.part', '.routers_groups.json' ] }
    auto_apply: dependents
    build_to: cache

  shelf_routing_generator:groups:
    import: package:shelf_routing_generator/run_routers_groups_builder.dart
    builder_factories: [ 'runRoutersGroupsBuilder' ]
    required_inputs: [ '.routers_groups.json' ]
    applies_builders: [ 'source_gen:combining_builder' ]
    build_extensions: { '.dart': [ '.routers.dart' ] }
    auto_apply: dependents
    build_to: source



